### ISSUE TITLE
typo in MailDelete warning message for Count adjustment

### ISSUE THREAD

**Issue by William-Rohm** [OfficeDev/Interop-MailSim#22]
In the MailDelete warning message

"Only 1000 email(s) are in the folder, so the number of emails to delete is adjusted from 1000 to 1"

it looks like the wrong variable is used for the first displayed number.

**Comment by v-am** [comment]
I'm not getting this message; I do get "Only 1 email(s) are in the folder, so the number of emails to delete is adjusted from 1000 to 1". The code looks correct as well.

**Comment by William-Rohm** [comment]
That is strange.  Here's my op and its sequence:
```  
 <MailDelete OperationName="OpMailDeleteFromJunk" Count="1000">
    <Folder>olFolderJunk</Folder>
    <Subject>MailSim Demo</Subject>
  </MailDelete>

  <Task Name="OpMailDeleteFromJunk" Iterations="1" Sleep="5"/>
```
And here's the warning from the log file:
```
<Warning Name="OpMailDeleteFromJunk" Time="8/13/2015 2:53:39 PM">
  <Detail>Only 1000 email(s) are in the folder, so the number of emails to delete is adjusted from 1000 to 1</Detail>
</Warning>
```
