### ISSUE TITLE
RandomAttachments directory name only works inline, not on its own line

### ISSUE THREAD

**Issue by William-Rohm** [OfficeDev/Interop-MailSim#23]
This works inline:

    <RandomAttachments Count="2">C:\MailSimDemo\DemoAttachments</RandomAttachments>

but a "directory doesn't exist" message is generated by this, with or without a trailing backslash:

```
   <RandomAttachments Count="2">
       C:\MailSimDemo\DemoAttachments
    </RandomAttachments>
```
The error message is:

```
8/13/2015 2:28:07 PM Error      : OpMailSendToARandomRecipient  : Directory
C:\MailSimDemo\DemoAttachments\
 doesn't exist, skipping attachment
```
which leads me to think that the parsing is taking the EOL characters along with the directory name string.

**Comment by v-am** [comment]
I can't reproduce it. Is this possible to attach the file that causes this issue?
