### ISSUE TITLE
LogFileLocation pathname requires trailing backslash

### ISSUE THREAD

**Issue by William-Rohm** [OfficeDev/Interop-MailSim#24]
This works:

```
    LogFileLocation="C:\MailSimDemo\Logs\"
```

But this ends up with the log files in C:\MailSimDemo, prepended with "Logs" (such as "Logs2015-08-13 14-11-07 V-WIROHM-3 Seq.xml"):

```
    LogFileLocation="C:\MailSimDemo\Logs"
```

**Comment by v-am** [comment]
I have a fix for that.

**Comment by v-am** [comment]
This has been fixed some time ago.
