### ISSUE TITLE
Need to update supported folder list in Operations.xsd

### ISSUE THREAD

**Issue by William-Rohm** [OfficeDev/Interop-MailSim#6]
The current Operations.xsd file includes a link to an MSDN list of supported Outlook folder names:

          <xs:element name="MailReply">
            <xs:complexType>
              <xs:sequence>
                
                <xs:element name="Folder" type="xs:string" />

The issue is that the MSDN list has more folder names than we currently support.  The references to the MSDN list should be changed to comments listing only the following folder names:

•	olFolderInbox
•	olFolderDrafts
•	olFolderSentMail
•	olFolderDeletedItems
•	olFolderJunk
•	olFolderOutbox

**Comment by mibowm** [comment]
Issue has been resolved.
